spring.application.name=Feata_2026
spring.config.import=optional:classpath:env.properties

server.port=

spring.datasource.url=${DB_URL:jdbc:mysql://100.124.43.116:3306/festa2026}
#spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/festa2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

r2.endpoint=https://2f59f81f48ee0c3340032aa91d361f58.r2.cloudflarestorage.com
r2.region=auto
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket=likelion-main
r2.base-url=https://cdn.syu-likelion.org
r2.profile-prefix=profile
r2.community-prefix=community